export const CHANGE_MESSAGE_INPUT_VALUE = "CHANGE_MESSAGE_INPUT_VALUE";
export const CHANGE_IMAGE_INPUT_VALUE = "CHANGE_IMAGE_INPUT_VALUE";

export const FETCH_GET_MESSAGES_SUCCESS = "FETCH_GET_MESSAGES_SUCCESS";
export const FETCH_GET_MESSAGES_ERROR = "FETCH_GET_MESSAGES_ERROR";